components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    userHeader:
      type: apiKey
      in: header
      name: user
      description: Nombre de usuario 

security:
  - bearerAuth: []
    userHeader: []